name: scanner_red
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Iconos base
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Herramientas de Red y Seguridad (Tu Suite)
  # Herramientas de Red y Seguridad (Tu Suite)
  network_info_plus: ^7.0.0
  permission_handler: ^12.0.1
  dartssh2: ^2.13.0
  url_launcher: ^6.3.2
  http: ^1.6.0
  multicast_dns: ^0.3.3
  wake_on_lan: ^4.1.1+3
  crypto: ^3.0.3
  path_provider: ^2.1.2
  dart_ping: ^9.0.1
  share_plus: ^12.0.1
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^6.1.0
  fl_chart: ^0.69.0
  provider: ^6.1.1
  pdf: ^3.10.8
  printing: ^5.11.1
  intl: ^0.19.0
  safe_device: ^1.3.8
  local_auth: ^2.1.6
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  http_certificate_pinning: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Configuración de Flutter
flutter:
  uses-material-design: true

# Configuración de tus Iconos
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21